import type { Metadata } from "next";
import { Checklist, DocCard, DocSection, PublicDocShell } from "@/components/PublicDocShell";

export const metadata: Metadata = { title: "Matching Guide | Parking Meeters", description: "Set up a profile and understand potential parking matches." };

export default function MatchingGuide() { return <PublicDocShell title="Matching" eyebrow="Support guide" intro="Matching compares member-provided details to find a possible timing and location fit. It is a coordination signal, not a parking guarantee.">
  <div className="grid gap-4 sm:grid-cols-2"><DocCard title="1. Set up your profile">Add your name or username, vehicle type, usual location, and the schedule you want to share. Use an approximate location when possible.</DocCard><DocCard title="2. Add schedules and vehicles">A departure schedule describes when you may leave; an arrival request describes when you are looking. Keep the vehicle details current so the signal is useful.</DocCard><DocCard title="3. Review a potential match">The service considers location proximity, overlapping time, compatibility, and account safety controls. Review the details before responding.</DocCard><DocCard title="4. Match Protocol acceptance">Open Messages to accept the match. A match is not active until both members accept, then a temporary message thread opens for coordination.</DocCard></div>
  <DocSection title="Match Protocol and SPOT Protocol"><p>Match Protocol is the mutual acceptance step in Messages. SPOT Arrival/Handoff Protocol is the separate, later safety flow used around arrival and the handoff. Accepting a match does not start arrival mode or guarantee a parking space.</p></DocSection>
  <DocSection title="Troubleshooting checklist"><Checklist items={["Confirm your schedule uses the correct date, time, and time zone.", "Check that your arrival area and vehicle type are current.", "Allow notifications, but also check the in-app activity or notification list.", "A potential match can expire, be declined, or disappear when schedules no longer overlap.", "Never treat a match as a reserved or guaranteed space; check signs when you arrive."]} /></DocSection>
</PublicDocShell>; }
