import Link from "next/link";
import { Metadata } from "next";
import { ArrowLeft, HeartHandshake, MapPin, ShieldCheck, Users } from "lucide-react";

export const metadata: Metadata = { title: "About Parking Meeters" };

export default function AboutPage() {
  return <main className="min-h-screen bg-[#f6f8f6] px-5 py-8 text-[#17211e] sm:px-8 sm:py-12"><div className="mx-auto max-w-4xl"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-[#e85d3f] hover:underline"><ArrowLeft className="h-4 w-4" />Back to Parking Meeters</Link><div className="mt-14 max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#e85d3f]">Why we exist</p><h1 className="mt-3 text-5xl font-bold leading-[1.02] tracking-[-0.05em] sm:text-6xl">Parking works better when people can coordinate.</h1><p className="mt-6 text-lg leading-8 text-[#71807b]">Parking Meeters helps a departing driver and an arriving driver find the right moment to connect. We are building a more useful layer between a busy curb and the people who depend on it.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-3">{[[HeartHandshake, "Cooperative by design", "We turn a frustrating solo search into a small, opt-in community exchange."], [MapPin, "Local first", "We start with focused three-block zones where timing and distance can actually line up."], [ShieldCheck, "Privacy forward", "We use approximate zones, mutual confirmation, and temporary communication by default."]].map(([Icon, title, description]) => <article key={title as string} className="rounded-3xl border border-[#dce3df] bg-white p-6"><Icon className="h-6 w-6 text-[#e85d3f]" /><h2 className="mt-6 font-bold">{title as string}</h2><p className="mt-2 text-sm leading-6 text-[#71807b]">{description as string}</p></article>)}</div><section className="mt-8 rounded-3xl bg-[#17211e] p-7 text-white sm:p-10"><Users className="h-6 w-6 text-[#f0c9a5]" /><h2 className="mt-6 text-2xl font-bold">Built for drivers, businesses, and neighborhoods</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-[#b7c3be]">Parking Meeters supports individual schedules, trusted business networks, safety education, and operational tools for communities working around the same parking pressure.</p><Link href="/contact" className="mt-7 inline-flex rounded-xl bg-[#e85d3f] px-4 py-3 text-sm font-bold text-white hover:bg-[#d84f33]">Talk with our team</Link></section></div></main>;
}
