import Link from "next/link";
import { Metadata } from "next";
import { ArrowLeft, BookOpen, Check, GraduationCap } from "lucide-react";

export const metadata: Metadata = { title: "Courses and Safety Education | Parking Meeters" };

export default function LearnPage() {
  return <main className="min-h-screen bg-zinc-50 px-5 py-8 text-zinc-900 sm:px-8 sm:py-12"><div className="mx-auto max-w-4xl"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600 hover:underline"><ArrowLeft className="h-4 w-4" />Back to Parking Meeters</Link><section className="mt-14 overflow-hidden rounded-3xl bg-[#17211e] p-7 text-white sm:p-12"><GraduationCap className="h-8 w-8 text-[#f0c9a5]" /><p className="mt-8 text-xs font-bold uppercase tracking-[0.18em] text-[#f0c9a5]">Learn the protocol</p><h1 className="mt-3 max-w-2xl text-4xl font-bold tracking-tight sm:text-5xl">Good handoffs start with good habits.</h1><p className="mt-5 max-w-xl text-base leading-7 text-[#b7c3be]">Our short courses help members understand how matching works, how to protect privacy, and how to arrive and depart without creating a safety problem.</p><Link href="/courses" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-[#e85d3f] px-5 py-3 text-sm font-bold text-white hover:bg-[#d84f33]">View available courses <BookOpen className="h-4 w-4" /></Link></section><div className="mt-8 grid gap-4 sm:grid-cols-3">{[["01", "Match basics", "Understand timing, zones, vehicle fit, and mutual confirmation."], ["02", "Safe arrival", "Use Arrival Mode responsibly and keep attention on the road."], ["03", "Community trust", "Learn reporting, privacy, no-payment rules, and respectful conduct."]].map(([number, title, description]) => <article key={number} className="rounded-2xl border border-zinc-200 bg-white p-6"><span className="text-xs font-black text-blue-600">{number}</span><h2 className="mt-7 font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-zinc-500">{description}</p><Check className="mt-6 h-4 w-4 text-emerald-600" /></article>)}</div><p className="mt-8 text-sm leading-6 text-zinc-500">Courses are educational and do not replace posted signs, local laws, safe driving practices, or emergency services. See the <Link href="/laws" className="text-blue-600 hover:underline">parking rules guide</Link> for official references.</p></div></main>;
}
