"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { createBrowserClient } from "@/lib/supabaseClient";

const config: Record<string, { resource: string; title: string; intro: string; fields: string[] }> = {
  time: { resource: "assessments", title: "TIME assessment", intro: "Timing, Information, Matching, and Engagement.", fields: ["section_key", "plain_language_assessment", "evidence_collected", "observations", "stakeholder_input", "known_risks", "opportunity_score", "confidence_level", "recommended_action", "open_questions"] },
  park: { resource: "assessments", title: "PARK assessment", intro: "Patterns, Access, Rules, and Knowledge.", fields: ["section_key", "plain_language_assessment", "evidence_collected", "observations", "stakeholder_input", "known_risks", "opportunity_score", "confidence_level", "recommended_action", "open_questions"] },
  "data-privacy": { resource: "assessments", title: "Data, privacy, accessibility, and trust", intro: "Capture the minimum data needed and the safeguards required.", fields: ["section_key", "plain_language_assessment", "data_sensitivity", "data_needed", "data_not_needed", "retention_proposal", "accessibility_implications", "fairness_implications", "mitigation_notes", "open_questions"] },
  opportunities: { resource: "opportunities", title: "Opportunities", intro: "Record recommendations without treating them as promises.", fields: ["title", "opportunity_type", "problem_addressed", "evidence_supporting", "affected_stakeholders", "client_value", "user_value", "privacy_considerations", "accessibility_considerations", "estimated_effort", "estimated_timeline", "risk_level", "confidence_level", "status", "recommended_next_step"] },
  pilot: { resource: "pilots", title: "Pilot workspace", intro: "Create a pilot concept with explicit scope, metrics, risks, and stop criteria.", fields: ["title", "status", "problem", "hypothesis", "target_users", "pilot_geography", "duration_text", "operating_owner", "features_included", "features_excluded", "data_collected", "data_not_collected", "accessibility_plan", "safety_plan", "baseline_conditions", "success_metrics", "decision_criteria", "stop_criteria", "risks", "assumptions"] },
  meetings: { resource: "meetings", title: "Meetings", intro: "Capture discovery conversations, decisions, and follow-up.", fields: ["title", "meeting_type", "starts_at", "ends_at", "participants", "agenda", "notes", "decisions", "follow_up"] },
  tasks: { resource: "tasks", title: "Tasks", intro: "Track next actions and follow-up.", fields: ["title", "description", "status", "priority", "due_at"] },
  resources: { resource: "resources", title: "Resources and sources", intro: "Store research references with reliability and takeaways.", fields: ["title", "resource_type", "source_organization", "source_url", "publication_date", "summary", "key_takeaways", "reliability_level", "relevant_framework", "notes"] },
};

export default function ClientWorkspaceSection({ params }: { params: { id: string; section: string } }) {
  const current = config[params.section];
  const [records, setRecords] = useState<Record<string, unknown>[]>([]);
  const [form, setForm] = useState<Record<string, string>>({});
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  useEffect(() => { if (!current) return; void load(); }, [params.id, params.section]);
  async function load() { const session = (await createBrowserClient().auth.getSession()).data.session; if (!session) return; const response = await fetch(`/api/admin/clients/${params.id}/workspace/${current.resource}`, { headers: { Authorization: `Bearer ${session.access_token}` } }); const body = await response.json(); if (response.ok) setRecords(body.records ?? []); }
  async function save(event: React.FormEvent) { event.preventDefault(); setMessage(""); setError(""); const session = (await createBrowserClient().auth.getSession()).data.session; if (!session) return; const body = { ...form, ...(current.resource === "assessments" ? { framework: params.section === "data-privacy" ? "privacy" : params.section.toUpperCase() } : {}) }; const response = await fetch(`/api/admin/clients/${params.id}/workspace/${current.resource}`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${session.access_token}` }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) setError(result.error || "Could not save record"); else { setMessage("Saved."); setForm({}); void load(); } }
  if (!current) return <main className="p-8"><p>Unknown Client File section.</p></main>;
  return <main className="mx-auto max-w-6xl p-6 sm:p-8"><Link href={`/admin/clients/${params.id}`} className="text-sm font-bold text-[#2457d6]">← Client overview</Link><h1 className="mt-5 text-4xl font-black">{current.title}</h1><p className="mt-2 text-sm text-zinc-500">{current.intro}</p><div className="mt-8 grid gap-6 lg:grid-cols-[24rem_1fr]"><form onSubmit={save} className="h-fit space-y-4 rounded-3xl border border-zinc-200 bg-white p-5"><h2 className="font-black">Add or update record</h2>{current.fields.map((field) => <label key={field} className="block text-sm font-bold">{field.replaceAll("_", " ")}<textarea value={form[field] || ""} onChange={(event) => setForm((values) => ({ ...values, [field]: event.target.value }))} rows={field.includes("notes") || field.includes("summary") || field.includes("assessment") || field.includes("problem") || field.includes("observation") || field.includes("evidence") ? 4 : 2} className="app-input mt-2 w-full rounded-xl px-3 py-2.5" /></label>)}<button className="w-full rounded-xl bg-[#2457d6] px-4 py-3 text-sm font-bold text-white">Save</button>{message && <p className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{message}</p>}{error && <p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}</form><section className="space-y-3">{records.length === 0 && <div className="rounded-2xl border border-dashed border-zinc-300 p-10 text-center text-sm text-zinc-500">No records yet.</div>}{records.map((record) => <article key={String(record.id)} className="rounded-2xl border border-zinc-200 bg-white p-5"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-black">{String(record.title || record.section_key || `${record.framework} assessment`)}</h2><span className="text-xs text-zinc-400">{String(record.status || record.confidence_level || "In progress")}</span></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-zinc-600">{String(record.plain_language_assessment || record.summary || record.problem || record.description || record.notes || record.evidence_supporting || "Record saved.")}</p></article>)}</section></div></main>;
}
