import Link from "next/link";
import { Metadata } from "next";
import { AlertTriangle, ArrowLeft, ExternalLink, Gavel, MapPin } from "lucide-react";

export const metadata: Metadata = { title: "Parking Laws and Rules | Parking Meeters" };

const resources = [
  ["City of Long Beach parking information", "Local signs, meters, permits, enforcement, and street-sweeping information.", "https://www.longbeach.gov/parking/"],
  ["California Vehicle Code", "State traffic and parking rules. The official code controls over any app information.", "https://leginfo.legislature.ca.gov/faces/codes.xhtml?lawCode=VEH"],
  ["Accessible parking guidance", "California information about disabled person parking placards and accessible spaces.", "https://www.dmv.ca.gov/portal/handbook/vehicle-industry-registration-procedures-manual-2/disabled-person-parking-placards/"],
];

export default function LawsPage() {
  return <main className="min-h-screen bg-white px-5 py-8 text-zinc-900 sm:px-8 sm:py-12"><div className="mx-auto max-w-4xl"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600 hover:underline"><ArrowLeft className="h-4 w-4" />Back to Parking Meeters</Link><header className="mt-14 max-w-2xl"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-amber-50 text-amber-600"><Gavel className="h-6 w-6" /></div><p className="mt-6 text-xs font-bold uppercase tracking-[0.18em] text-blue-600">Know before you park</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Parking rules belong to the street.</h1><p className="mt-4 text-base leading-7 text-zinc-600">Parking Meeters can help coordinate a possible handoff, but it cannot change a sign, extend a time limit, reserve a public space, or override enforcement.</p></header><div className="mt-10 rounded-2xl border border-red-200 bg-red-50 p-5 text-sm leading-6 text-red-900"><AlertTriangle className="mb-2 h-5 w-5" /><strong>Always read the sign where you park.</strong> If this page conflicts with a posted sign, official notice, city rule, or law, follow the official source.</div><section className="mt-10"><h2 className="text-2xl font-bold">Official references</h2><div className="mt-5 grid gap-4">{resources.map(([title, description, href]) => <a key={title} href={href} target="_blank" rel="noreferrer" className="flex items-start gap-4 rounded-2xl border border-zinc-200 p-5 transition hover:border-blue-300 hover:shadow-sm"><span className="rounded-xl bg-blue-50 p-3 text-blue-600"><MapPin className="h-5 w-5" /></span><span className="flex-1"><strong className="block">{title}</strong><span className="mt-1 block text-sm leading-6 text-zinc-500">{description}</span></span><ExternalLink className="h-4 w-4 shrink-0 text-zinc-400" /></a>)}</div></section><section className="mt-10 grid gap-4 sm:grid-cols-2"><article className="rounded-2xl bg-zinc-50 p-6"><h2 className="font-bold">Parking Meeters never allows</h2><p className="mt-3 text-sm leading-6 text-zinc-600">Blocking driveways, sidewalks, fire lanes, accessible spaces, crosswalks, or travel lanes. Waiting unsafely or creating a traffic conflict is never an acceptable handoff.</p></article><article className="rounded-2xl bg-zinc-50 p-6"><h2 className="font-bold">Need help?</h2><p className="mt-3 text-sm leading-6 text-zinc-600">Read our <Link href="/legal/community-guidelines" className="text-blue-600 hover:underline">Community Guidelines</Link> and <Link href="/support/reporting" className="text-blue-600 hover:underline">safety reporting guide</Link>.</p></article></section></div></main>;
}
