import Link from "next/link";
import { Metadata } from "next";
import { ArrowLeft, Cookie } from "lucide-react";

export const metadata: Metadata = { title: "Cookies and Technologies | Parking Meeters" };

export default function CookiesPage() {
  return <main className="min-h-screen bg-zinc-50 px-5 py-8 text-zinc-900 sm:px-8 sm:py-12"><article className="mx-auto max-w-3xl"><Link href="/legal" className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600 hover:underline"><ArrowLeft className="h-4 w-4" />Legal Center</Link><header className="mt-12 border-b border-zinc-200 pb-8"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-amber-50 text-amber-600"><Cookie className="h-6 w-6" /></div><h1 className="mt-6 text-4xl font-bold tracking-tight">Cookies and Technologies</h1><p className="mt-3 text-sm text-zinc-500">Parking Meeters · Last updated: September 2026</p></header><div className="space-y-8 py-8 text-sm leading-7 text-zinc-700"><section><h2 className="text-xl font-bold text-zinc-900">What we use</h2><p className="mt-3">Parking Meeters may use cookies, browser storage, service-worker storage, and similar technologies to keep you signed in, remember preferences, support the installable app, protect accounts, and understand basic product performance.</p></section><section><h2 className="text-xl font-bold text-zinc-900">Essential technologies</h2><p className="mt-3">Authentication and security technologies are needed for account sessions, fraud prevention, consent records, and safe access to protected features. Turning these off may prevent the app from working.</p></section><section><h2 className="text-xl font-bold text-zinc-900">Optional technologies</h2><p className="mt-3">If optional analytics, marketing, or notification technologies are enabled in a future release, we will identify their purpose and provide any controls required by applicable law. Browser settings can also limit or delete stored technologies.</p></section><section><h2 className="text-xl font-bold text-zinc-900">Questions</h2><p className="mt-3">For privacy or technology questions, contact <a href="mailto:privacy@parkingmeeters.com" className="text-blue-600 hover:underline">privacy@parkingmeeters.com</a>. See our <Link href="/privacy-policy" className="text-blue-600 hover:underline">Privacy Policy</Link> for information about personal data.</p></section></div></article></main>;
}
