"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { createBrowserClient } from "@/lib/supabaseClient";

export default function NewClientPage() {
  const router = useRouter();
  const [form, setForm] = useState({ display_name: "", client_type: "Business Improvement District", relationship_status: "Prospect", priority: "Medium", city: "", study_area_name: "", primary_parking_challenge: "", next_follow_up_at: "" });
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); const session = (await createBrowserClient().auth.getSession()).data.session; if (!session) { setError("Your session has expired."); setSaving(false); return; } const response = await fetch("/api/admin/clients", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${session.access_token}` }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) { setError(body.error || "Could not create client file"); setSaving(false); return; } router.push(`/admin/clients/${body.client.id}`); }
  return <main className="mx-auto max-w-3xl p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#e85d3f]">Onsite quick create</p><h1 className="mt-2 text-4xl font-black">Create a client file</h1><p className="mt-3 text-sm text-[#71807b]">Start with the minimum record. You can complete the assessment progressively.</p><form onSubmit={submit} className="mt-8 space-y-5 rounded-3xl border border-zinc-200 bg-white p-6 shadow-sm"><Field label="Organization or client name" required value={form.display_name} onChange={(value) => update("display_name", value)} /><div className="grid gap-5 sm:grid-cols-2"><Select label="Client type" value={form.client_type} options={["Business Improvement District", "Downtown association", "City or public agency", "Parking operator", "Property manager", "Venue", "Employer", "Other"]} onChange={(value) => update("client_type", value)} /><Select label="Relationship status" value={form.relationship_status} options={["Researching", "Prospect", "Warm lead", "Discovery scheduled", "Active client", "Not a fit"]} onChange={(value) => update("relationship_status", value)} /></div><div className="grid gap-5 sm:grid-cols-2"><Select label="Priority" value={form.priority} options={["Low", "Medium", "High", "Urgent"]} onChange={(value) => update("priority", value)} /><Field label="City or region" value={form.city} onChange={(value) => update("city", value)} /></div><Field label="Study area or site" value={form.study_area_name} onChange={(value) => update("study_area_name", value)} /><label className="block text-sm font-bold">Primary parking challenge<textarea value={form.primary_parking_challenge} onChange={(event) => update("primary_parking_challenge", event.target.value)} rows={4} className="app-input mt-2 w-full rounded-xl px-4 py-3" placeholder="What appears to be happening?" /></label><label className="block text-sm font-bold">Next follow-up date<input type="date" value={form.next_follow_up_at} onChange={(event) => update("next_follow_up_at", event.target.value)} className="app-input mt-2 rounded-xl px-4 py-3" /></label>{error && <p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<div className="flex justify-end gap-3"><button type="button" onClick={() => router.back()} className="rounded-xl border border-zinc-200 px-4 py-3 text-sm font-bold">Cancel</button><button disabled={saving} className="rounded-xl bg-[#2457d6] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{saving ? "Creating..." : "Create client file"}</button></div></form></main>;
}

function Field({ label, value, onChange, required }: { label: string; value: string; onChange: (value: string) => void; required?: boolean }) { return <label className="block text-sm font-bold">{label}<input required={required} value={value} onChange={(event) => onChange(event.target.value)} className="app-input mt-2 w-full rounded-xl px-4 py-3" /></label>; }
function Select({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label className="block text-sm font-bold">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="app-input mt-2 w-full rounded-xl px-4 py-3">{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
