"use client";
import { useEffect, useState } from "react";
import { osmImportFetch } from "../client";

export default function RecordsPage() {
  const [records, setRecords] = useState<any[] | null>(null);
  const [reason, setReason] = useState("");
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  useEffect(() => { void (async () => { try { const response = await osmImportFetch("/api/admin/osm-import/records"); const data = await response.json(); if (!response.ok) throw new Error(data.error); setRecords(data.records || []); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load records"); } })(); }, []);
  async function review(id: string, action: string) { if (!reason.trim()) { setError("A reason is required for every review action."); return; } const response = await osmImportFetch("/api/admin/osm-import/records", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, action, reason: reason.trim() }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "Review action failed"); return; } setRecords((old) => old?.map((record) => record.id === id ? { ...record, import_status: data.record?.import_status || (action === "approve" ? "approved" : "rejected") } : record) || null); setMessage(`${action[0].toUpperCase()}${action.slice(1)} saved.`); }
  async function publish(id: string) { if (!reason.trim()) { setError("A reason is required before publishing."); return; } if (!window.confirm("Publish this approved record to app-facing parking_information?")) return; const response = await osmImportFetch("/api/admin/osm-import/publish", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ record_ids: [id], reason: reason.trim() }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "Publication failed"); return; } setRecords((old) => old?.map((record) => record.id === id ? { ...record, import_status: "published" } : record) || null); setMessage("Published to app-facing parking information."); }
  return <main className="mx-auto max-w-6xl p-5 md:p-10"><h1 className="text-3xl font-black text-blue-950">Staged Parking Records</h1><p className="mt-2 text-sm text-zinc-600">Review source tags and geometry before publication. Duplicate flags never merge automatically.</p><div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><strong>Approve is not publish.</strong> Approve marks a staged record as ready for admin publication. Publish sends it to app-facing <code>parking_information</code>. OSM data is reference data and may be incomplete or out of date.</div><input className="mt-5 w-full rounded-xl border p-3" placeholder="Reason required for every review action and publication" value={reason} onChange={(event) => setReason(event.target.value)} />{message && <p className="mt-3 text-sm font-semibold text-green-700">{message}</p>}{error && <p className="mt-3 text-sm font-semibold text-red-700">{error}</p>}{records === null ? <p className="mt-6">Loading records...</p> : <div className="mt-5 grid gap-3">{records.length ? records.map((record) => <article key={record.id} className="rounded-2xl border bg-white p-4"><div className="flex flex-wrap justify-between gap-2"><div><h2 className="font-bold">{record.name}</h2><p className="text-sm text-zinc-600">{record.parking_type} · {record.access} · fee: {record.fee} · Mapped area geometry</p></div><span className="text-xs font-bold uppercase">{record.import_status}</span></div>{record.duplicate_confidence > 0 && <p className="mt-2 text-xs text-amber-700">Possible duplicate ({Math.round(record.duplicate_confidence * 100)}%); inspect before approving.</p>}<div className="mt-3 flex flex-wrap gap-2"><button className="rounded-lg bg-green-700 px-3 py-2 text-xs font-bold text-white disabled:opacity-50" disabled={record.import_status === "published"} onClick={() => void review(record.id, "approve")}>Approve</button><button className="rounded-lg bg-red-700 px-3 py-2 text-xs font-bold text-white" onClick={() => void review(record.id, "reject")}>Reject</button>{record.import_status === "approved" && <button className="rounded-lg bg-blue-800 px-3 py-2 text-xs font-bold text-white" onClick={() => void publish(record.id)}>Publish</button>}</div></article>) : <p>No staged records found.</p>}</div>}</main>;
}
