"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { createBrowserClient } from "@/lib/supabaseClient";

const fields = ["primary_contact_name", "primary_contact_role", "primary_contact_email", "primary_contact_phone", "decision_maker_contact", "operational_contact", "known_peak_periods", "known_upcoming_events", "existing_solutions", "known_stakeholders", "known_constraints", "known_data_sources", "why_relevant", "validation_questions", "potential_first_engagement", "client_urgency", "decision_timeline", "success_definition", "internal_notes"];
const labels: Record<string, string> = { primary_contact_name: "Primary contact", primary_contact_role: "Contact role", primary_contact_email: "Contact email", primary_contact_phone: "Contact phone", decision_maker_contact: "Decision-maker contact", operational_contact: "Operational contact", known_peak_periods: "Known peak periods", known_upcoming_events: "Known upcoming events", existing_solutions: "Existing solutions", known_stakeholders: "Known stakeholders", known_constraints: "Known constraints", known_data_sources: "Known data sources", why_relevant: "Why Parking Meeters may be relevant", validation_questions: "What must be validated", potential_first_engagement: "Potential first engagement", client_urgency: "Client urgency", decision_timeline: "Decision timeline", success_definition: "Success definition in client words", internal_notes: "Internal notes" };

export default function ClientIntakePage({ params }: { params: { id: string } }) {
  const [values, setValues] = useState<Record<string, string>>({}); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { void (async () => { const session = (await createBrowserClient().auth.getSession()).data.session; if (!session) return; const response = await fetch(`/api/admin/clients/${params.id}`, { headers: { Authorization: `Bearer ${session.access_token}` } }); const body = await response.json(); if (body.intake) setValues(body.intake); })(); }, [params.id]);
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); setError(""); const session = (await createBrowserClient().auth.getSession()).data.session; if (!session) return; const response = await fetch(`/api/admin/clients/${params.id}/intake`, { method: "PUT", headers: { "Content-Type": "application/json", Authorization: `Bearer ${session.access_token}` }, body: JSON.stringify(values) }); const body = await response.json(); if (!response.ok) setError(body.error || "Could not save intake"); else setMessage("Intake saved."); setSaving(false); }
  return <main className="mx-auto max-w-4xl p-6 sm:p-8"><Link href={`/admin/clients/${params.id}`} className="text-sm font-bold text-[#2457d6]">← Client overview</Link><h1 className="mt-5 text-4xl font-black">Client intake</h1><p className="mt-2 text-sm text-zinc-500">Progressive discovery record. Keep facts labeled and separate from assumptions.</p><form onSubmit={save} className="mt-8 grid gap-5 rounded-3xl border border-zinc-200 bg-white p-6 sm:grid-cols-2">{fields.map((field) => <label key={field} className={`block text-sm font-bold ${field === "internal_notes" || field === "primary_parking_challenge" ? "sm:col-span-2" : ""}`}>{labels[field]}<textarea value={values[field] || ""} onChange={(event) => setValues((current) => ({ ...current, [field]: event.target.value }))} rows={field === "internal_notes" ? 5 : 3} className="app-input mt-2 w-full rounded-xl px-4 py-3" /></label>)}<label className="block text-sm font-bold">Evidence label<select value={values.evidence_label || "Reported"} onChange={(event) => setValues((current) => ({ ...current, evidence_label: event.target.value }))} className="app-input mt-2 w-full rounded-xl px-4 py-3"><option>Observed</option><option>Reported</option><option>Official</option><option>Estimated</option><option>Forecast</option><option>Proposed</option><option>Requires validation</option></select></label><div className="flex items-end justify-end sm:col-span-2"><button disabled={saving} className="rounded-xl bg-[#2457d6] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{saving ? "Saving..." : "Save intake"}</button></div>{message && <p className="sm:col-span-2 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{message}</p>}{error && <p className="sm:col-span-2 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}</form></main>;
}
