import { NextRequest, NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabaseAdmin";
import { getAuthenticatedUser } from "@/lib/api/auth-helpers";
import { isVehicleType, isValidUuid } from "@/lib/schedule-validation";

async function getAuth(request: NextRequest) { const user = await getAuthenticatedUser(request); return user ? { user, db: createAdminClient() } : null; }
function validate(body: Record<string, unknown>) { if (!isVehicleType(body.vehicle_type)) return "A valid vehicle type is required"; if (body.nickname != null && (typeof body.nickname !== "string" || body.nickname.length > 80)) return "Nickname must be 80 characters or fewer"; for (const key of ["make_model", "color"]) if (body[key] != null && (typeof body[key] !== "string" || String(body[key]).length > 80)) return `${key} must be 80 characters or fewer`; return null; }
export async function GET(request: NextRequest) { const a = await getAuth(request); if (!a) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { data, error } = await a.db.from("user_vehicles").select("*").eq("user_id", a.user.id).order("is_primary", { ascending: false }).order("created_at"); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); return NextResponse.json({ vehicles: data ?? [] }); }
export async function POST(request: NextRequest) { const a = await getAuth(request); if (!a) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); try { const body = await request.json() as Record<string, unknown>; const invalid = validate(body); if (invalid) return NextResponse.json({ error: invalid }, { status: 400 }); if (body.is_primary) await a.db.from("user_vehicles").update({ is_primary: false }).eq("user_id", a.user.id); const { data, error } = await a.db.from("user_vehicles").insert({ user_id: a.user.id, nickname: body.nickname ?? "My vehicle", vehicle_type: body.vehicle_type, make_model: body.make_model ?? null, color: body.color ?? null, is_primary: body.is_primary ?? false, active: body.active ?? true }).select().single(); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); return NextResponse.json({ vehicle: data }, { status: 201 }); } catch { return NextResponse.json({ error: "Invalid request body" }, { status: 400 }); } }
export async function PATCH(request: NextRequest) { const a = await getAuth(request); if (!a) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const id = new URL(request.url).searchParams.get("id"); if (!id || !isValidUuid(id)) return NextResponse.json({ error: "Valid vehicle ID is required" }, { status: 400 }); try { const body = await request.json() as Record<string, unknown>; const { data: current } = await a.db.from("user_vehicles").select("*").eq("id", id).eq("user_id", a.user.id).maybeSingle(); if (!current) return NextResponse.json({ error: "Vehicle not found" }, { status: 404 }); const merged = { ...current, ...body }; const invalid = validate(merged); if (invalid) return NextResponse.json({ error: invalid }, { status: 400 }); if (body.is_primary === true) await a.db.from("user_vehicles").update({ is_primary: false }).eq("user_id", a.user.id); const allowed = ["nickname", "vehicle_type", "make_model", "color", "is_primary", "active"]; const update = Object.fromEntries(allowed.filter((key) => key in body).map((key) => [key, body[key]])); const { data, error } = await a.db.from("user_vehicles").update(update).eq("id", id).eq("user_id", a.user.id).select().single(); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); return NextResponse.json({ vehicle: data }); } catch { return NextResponse.json({ error: "Invalid request body" }, { status: 400 }); } }
export async function DELETE(request: NextRequest) { const a = await getAuth(request); if (!a) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const id = new URL(request.url).searchParams.get("id"); if (!id || !isValidUuid(id)) return NextResponse.json({ error: "Valid vehicle ID is required" }, { status: 400 }); const { error } = await a.db.from("user_vehicles").update({ active: false, is_primary: false }).eq("id", id).eq("user_id", a.user.id); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); return NextResponse.json({ success: true }); }
