"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, CalendarClock, Car, Pencil, Trash2 } from "lucide-react";
import { createBrowserClient } from "@/lib/supabaseClient";
import { VEHICLE_TYPES, getVehicleTypeLabel } from "@/lib/vehicle-types";

type Vehicle = { id: string; nickname: string; vehicle_type: string; make_model: string | null; color: string | null; is_primary: boolean; active: boolean };
type Schedule = { id: string; label: string; latitude: number; longitude: number; days_of_week: number[]; departure_time: string; return_time: string; start_date: string | null; end_date: string | null; vehicle_id: string | null };
type Entry = { id: string; label: string; latitude: number; longitude: number; schedule_date: string; arrival_time: string; departure_time: string; vehicle_id: string | null };
type FormState = { label: string; latitude: string; longitude: string; vehicle_id: string; [key: string]: unknown };

const DAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const today = () => new Date().toISOString().slice(0, 10);
const input = "app-input mt-1 w-full rounded-xl border px-3 py-2.5 text-sm";

export default function SchedulePlannerPage() {
  const supabase = createBrowserClient();
  const [token, setToken] = useState("");
  const [vehicles, setVehicles] = useState<Vehicle[]>([]);
  const [schedules, setSchedules] = useState<Schedule[]>([]);
  const [entries, setEntries] = useState<Entry[]>([]);
  const [primaryArea, setPrimaryArea] = useState<{ latitude: number; longitude: number } | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [scheduleForm, setScheduleForm] = useState<FormState>({ label: "", latitude: "", longitude: "", days_of_week: [1, 2, 3, 4, 5], departure_time: "17:00", return_time: "08:00", start_date: "", end_date: "", vehicle_id: "" });
  const [entryForm, setEntryForm] = useState<FormState>({ label: "", latitude: "", longitude: "", schedule_date: today(), arrival_time: "08:00", departure_time: "17:00", vehicle_id: "" });
  const [editingSchedule, setEditingSchedule] = useState<string | null>(null);
  const [editingEntry, setEditingEntry] = useState<string | null>(null);

  const load = async (accessToken: string) => {
    const headers = { Authorization: `Bearer ${accessToken}` };
    const [v, s, e, p] = await Promise.all([
      fetch("/api/vehicles", { headers }), fetch("/api/schedules", { headers }),
      fetch("/api/schedule-entries", { headers }), fetch("/api/parking-spots/get", { headers }),
    ]);
    const [vj, sj, ej, pj] = await Promise.all([v.json(), s.json(), e.json(), p.json()]);
    if (!v.ok || !s.ok || !e.ok || !p.ok) throw new Error(vj.error || sj.error || ej.error || pj.error || "Could not load planner");
    setVehicles(vj.vehicles ?? []); setSchedules(sj.schedules ?? []); setEntries(ej.entries ?? []);
    const area = (pj.spots ?? []).find((spot: { label?: string }) => spot.label === "Primary commute area") ?? pj.spots?.[0];
    const coords = area && Number.isFinite(Number(area.latitude)) && Number.isFinite(Number(area.longitude))
      ? { latitude: Number(area.latitude), longitude: Number(area.longitude) } : null;
    setPrimaryArea(coords);
    if (coords) {
      setScheduleForm((form) => ({ ...form, latitude: String(coords.latitude), longitude: String(coords.longitude) }));
      setEntryForm((form) => ({ ...form, latitude: String(coords.latitude), longitude: String(coords.longitude) }));
    }
  };

  useEffect(() => { void (async () => { const { data: { session } } = await supabase.auth.getSession(); if (!session) { window.location.href = "/"; return; } setToken(session.access_token); try { await load(session.access_token); } catch (e) { setError(e instanceof Error ? e.message : "Could not load planner"); } finally { setLoading(false); } })(); }, []);
  const request = async (url: string, options: RequestInit) => { const response = await fetch(url, { ...options, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` } }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Request failed"); return body; };
  const remove = async (url: string, name: string) => { if (!window.confirm(`Remove this ${name}?`)) return; try { await request(url, { method: "DELETE" }); await load(token); } catch (e) { setError(e instanceof Error ? e.message : "Could not remove item"); } };
  const saveSchedule = async (event: React.FormEvent) => { event.preventDefault(); if (!primaryArea) { setError("Set up a primary parking area in your profile before saving a schedule."); return; } try { await request(editingSchedule ? `/api/schedules?id=${editingSchedule}` : "/api/schedules", { method: editingSchedule ? "PATCH" : "POST", body: JSON.stringify({ ...scheduleForm, latitude: Number(scheduleForm.latitude), longitude: Number(scheduleForm.longitude), start_date: scheduleForm.start_date || null, end_date: scheduleForm.end_date || null, vehicle_id: scheduleForm.vehicle_id || null }) }); setEditingSchedule(null); await load(token); } catch (e) { setError(e instanceof Error ? e.message : "Could not save weekly schedule"); } };
  const saveEntry = async (event: React.FormEvent) => { event.preventDefault(); if (!primaryArea) { setError("Set up a primary parking area in your profile before saving a date entry."); return; } try { await request(editingEntry ? `/api/schedule-entries?id=${editingEntry}` : "/api/schedule-entries", { method: editingEntry ? "PATCH" : "POST", body: JSON.stringify({ ...entryForm, latitude: Number(entryForm.latitude), longitude: Number(entryForm.longitude), vehicle_id: entryForm.vehicle_id || null }) }); setEditingEntry(null); await load(token); } catch (e) { setError(e instanceof Error ? e.message : "Could not save date entry"); } };

  if (loading) return <main className="app-page flex min-h-screen items-center justify-center text-sm text-[var(--app-muted)]">Loading your schedule planner...</main>;
  return <main className="app-page min-h-screen px-4 py-6 text-[var(--app-ink)] sm:px-8 sm:py-10"><div className="mx-auto max-w-4xl"><Link href="/profile" className="app-link inline-flex items-center gap-2 text-sm font-bold"><ArrowLeft className="h-4 w-4" /> Profile</Link><header className="mt-6"><p className="text-xs font-black uppercase tracking-[0.18em] text-[var(--app-accent)]">Private planning</p><h1 className="mt-2 text-4xl font-black tracking-tight">Schedule planner</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--app-muted)]">Schedules are private by default and used for potential matching. They are not reservations or guarantees.</p></header>{error && <p role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <PlannerSection title="Vehicles" icon={<Car className="h-5 w-5 text-[var(--app-accent)]" />}><div className="grid gap-3 sm:grid-cols-2">{vehicles.filter((v) => v.active).map((v) => <div key={v.id} className="rounded-xl border border-[var(--app-border)] p-4"><p className="font-bold">{v.nickname} {v.is_primary && <span className="text-xs text-[var(--app-accent)]">Primary</span>}</p><p className="text-sm text-[var(--app-muted)]">{getVehicleTypeLabel(v.vehicle_type)}{v.make_model ? ` · ${v.make_model}` : ""}{v.color ? ` · ${v.color}` : ""}</p></div>)}</div></PlannerSection>
    <PlannerSection title="Weekly schedules" icon={<CalendarClock className="h-5 w-5 text-[var(--app-accent)]" />}><div className="space-y-3">{schedules.map((s) => <div key={s.id} className="rounded-xl border border-[var(--app-border)] p-4"><div className="flex justify-between gap-3"><div><p className="font-bold">{s.label}</p><p className="text-sm text-[var(--app-muted)]">{s.days_of_week.map((d) => DAYS[d]).join(" · ")} · arrival {s.return_time.slice(0, 5)} · departure {s.departure_time.slice(0, 5)}</p><p className="text-xs text-[var(--app-muted)]">{s.start_date || "Today onward"} to {s.end_date || "No end date"} · Area saved privately</p></div><div className="flex gap-1"><button onClick={() => { setEditingSchedule(s.id); setScheduleForm({ label: s.label, latitude: String(s.latitude), longitude: String(s.longitude), days_of_week: s.days_of_week, departure_time: s.departure_time.slice(0, 5), return_time: s.return_time.slice(0, 5), start_date: s.start_date || "", end_date: s.end_date || "", vehicle_id: s.vehicle_id || "" }); }} aria-label={`Edit ${s.label}`} className="p-2"><Pencil className="h-4 w-4" /></button><button onClick={() => void remove(`/api/schedules?id=${s.id}`, "weekly schedule")} aria-label={`Remove ${s.label}`} className="p-2 text-red-600"><Trash2 className="h-4 w-4" /></button></div></div></div>)}</div><ScheduleForm form={scheduleForm} setForm={setScheduleForm} onSubmit={saveSchedule} editing={Boolean(editingSchedule)} /></PlannerSection>
    <PlannerSection title="Specific dates" icon={<CalendarClock className="h-5 w-5 text-[var(--app-accent)]" />}><p className="text-sm text-[var(--app-muted)]">Add multiple one-off arrival and departure plans. New entries default to today.</p><div className="mt-4 space-y-3">{entries.map((e) => <div key={e.id} className="rounded-xl border border-[var(--app-border)] p-4"><div className="flex justify-between gap-3"><div><p className="font-bold">{e.label} · {new Date(`${e.schedule_date}T00:00:00`).toLocaleDateString()}</p><p className="text-sm text-[var(--app-muted)]">arrival {e.arrival_time.slice(0, 5)} · departure {e.departure_time.slice(0, 5)}</p><p className="text-xs text-[var(--app-muted)]">Area saved privately</p></div><div className="flex gap-1"><button onClick={() => { setEditingEntry(e.id); setEntryForm({ label: e.label, latitude: String(e.latitude), longitude: String(e.longitude), schedule_date: e.schedule_date, arrival_time: e.arrival_time.slice(0, 5), departure_time: e.departure_time.slice(0, 5), vehicle_id: e.vehicle_id || "" }); }} aria-label={`Edit ${e.label}`} className="p-2"><Pencil className="h-4 w-4" /></button><button onClick={() => void remove(`/api/schedule-entries?id=${e.id}`, "date entry")} aria-label={`Remove ${e.label}`} className="p-2 text-red-600"><Trash2 className="h-4 w-4" /></button></div></div></div>)}</div><EntryForm form={entryForm} setForm={setEntryForm} onSubmit={saveEntry} editing={Boolean(editingEntry)} /></PlannerSection></div></main>;
}

function PlannerSection({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="app-card mt-6 p-5 sm:p-6"><h2 className="flex items-center gap-2 text-xl font-black">{icon}{title}</h2>{children}</section>; }
function AreaNotice({ form }: { form: FormState }) { return <><p className="rounded-xl border border-[var(--app-border)] bg-[var(--app-surface)] p-3 text-xs font-semibold text-[var(--app-muted)] sm:col-span-2">{form.latitude && form.longitude ? "Area saved privately" : "Set up a primary parking area in your profile first."}</p><input type="hidden" value={form.latitude} readOnly /><input type="hidden" value={form.longitude} readOnly /></>; }
function ScheduleForm({ form, setForm, onSubmit, editing }: { form: FormState; setForm: (v: FormState) => void; onSubmit: (e: React.FormEvent) => void; editing: boolean }) { return <form onSubmit={onSubmit} className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">Area / label<input required className={input} value={form.label} onChange={(e) => setForm({ ...form, label: e.target.value })} /></label><label className="text-xs font-bold">Vehicle<input className={input} value={form.vehicle_id} onChange={(e) => setForm({ ...form, vehicle_id: e.target.value })} placeholder="Vehicle ID, optional" /></label><AreaNotice form={form} /><label className="text-xs font-bold">Arrival<input required type="time" className={input} value={String(form.return_time)} onChange={(e) => setForm({ ...form, return_time: e.target.value })} /></label><label className="text-xs font-bold">Departure<input required type="time" className={input} value={String(form.departure_time)} onChange={(e) => setForm({ ...form, departure_time: e.target.value })} /></label><label className="text-xs font-bold">Start date<input type="date" className={input} value={String(form.start_date)} onChange={(e) => setForm({ ...form, start_date: e.target.value })} /></label><label className="text-xs font-bold">End date<input type="date" className={input} value={String(form.end_date)} onChange={(e) => setForm({ ...form, end_date: e.target.value })} /></label><button className="app-primary rounded-xl px-4 py-3 text-sm font-bold sm:col-span-2">{editing ? "Update weekly schedule" : "Add weekly schedule"}</button></form>; }
function EntryForm({ form, setForm, onSubmit, editing }: { form: FormState; setForm: (v: FormState) => void; onSubmit: (e: React.FormEvent) => void; editing: boolean }) { return <form onSubmit={onSubmit} className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">Area / label<input required className={input} value={form.label} onChange={(e) => setForm({ ...form, label: e.target.value })} /></label><label className="text-xs font-bold">Date<input required type="date" className={input} value={String(form.schedule_date)} onChange={(e) => setForm({ ...form, schedule_date: e.target.value })} /></label><AreaNotice form={form} /><label className="text-xs font-bold">Arrival<input required type="time" className={input} value={String(form.arrival_time)} onChange={(e) => setForm({ ...form, arrival_time: e.target.value })} /></label><label className="text-xs font-bold">Departure<input required type="time" className={input} value={String(form.departure_time)} onChange={(e) => setForm({ ...form, departure_time: e.target.value })} /></label><button className="app-primary rounded-xl px-4 py-3 text-sm font-bold sm:col-span-2">{editing ? "Update date entry" : "Add date entry"}</button></form>; }
