"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ClipboardList, Eye, FileText, Flag, Users } from "lucide-react";
import { createBrowserClient } from "@/lib/supabaseClient";

type ClientFile = { id: string; internal_reference: string; display_name: string; client_type: string; relationship_status: string; engagement_status: string; priority: string; confidentiality_level: string; city: string | null; study_area_name: string | null; primary_parking_challenge: string | null; next_follow_up_at: string | null; updated_at: string };
type ClientData = { client: ClientFile; intake: Record<string, unknown> | null; observations: Array<{ id: string; title: string; finding_summary: string | null; observed_at: string }>; stakeholders: Array<{ id: string; name: string; organization: string | null; role: string | null }>; timeline: Array<{ id: string; event_type: string; summary: string; created_at: string }> };

export default function ClientFilePage({ params }: { params: { id: string } }) {
  const [data, setData] = useState<ClientData | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { void (async () => { const session = (await createBrowserClient().auth.getSession()).data.session; if (!session) return; const response = await fetch(`/api/admin/clients/${params.id}`, { headers: { Authorization: `Bearer ${session.access_token}` }, cache: "no-store" }); const body = await response.json(); if (!response.ok) setError(body.error || "Could not load client file"); else setData(body); })(); }, [params.id]);
  if (error) return <main className="p-8"><p className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p></main>;
  if (!data) return <main className="p-8 text-sm text-zinc-500">Loading client file...</main>;
  const { client } = data;
  const links = [{ href: "intake", label: "Intake", icon: ClipboardList }, { href: "observations", label: "Observations", icon: Eye }, { href: "stakeholders", label: "Stakeholders", icon: Users }, { href: "time", label: "TIME assessment", icon: FileText }, { href: "park", label: "PARK assessment", icon: FileText }, { href: "data-privacy", label: "Data & privacy", icon: Flag }, { href: "opportunities", label: "Opportunities", icon: FileText }, { href: "pilot", label: "Pilot workspace", icon: FileText }, { href: "meetings", label: "Meetings", icon: FileText }, { href: "tasks", label: "Tasks", icon: ClipboardList }, { href: "resources", label: "Resources", icon: FileText }, { href: "timeline", label: "Timeline", icon: FileText }];
  return <main className="mx-auto max-w-6xl p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#e85d3f]">{client.internal_reference} · Confidential client file</p><h1 className="mt-2 text-4xl font-black tracking-[-0.05em]">{client.display_name}</h1><p className="mt-2 text-sm text-[#71807b]">{client.client_type} · {client.city || "Location not set"} · {client.study_area_name || "Study area not set"}</p></div><div className="flex gap-2 text-xs font-bold"><span className="rounded-full bg-blue-50 px-3 py-2 text-blue-700">{client.relationship_status}</span><span className="rounded-full bg-zinc-100 px-3 py-2 text-zinc-600">{client.priority} priority</span></div></div><section className="mt-8 grid gap-4 sm:grid-cols-3"><Stat label="Engagement" value={client.engagement_status} /><Stat label="Follow-up" value={client.next_follow_up_at ? new Date(client.next_follow_up_at).toLocaleDateString() : "Not scheduled"} /><Stat label="Observations" value={String(data.observations.length)} /></section><section className="mt-8 rounded-3xl border border-[#f0c9a5] bg-[#fff8f3] p-5"><div className="flex items-start gap-3"><Flag className="mt-0.5 text-[#e85d3f]" size={19} /><div><p className="text-xs font-black uppercase tracking-wider text-[#b93d29]">Professional boundary</p><p className="mt-1 text-sm leading-6 text-[#6e5045]">Internal working record. Do not treat this file as legal advice, a parking reservation, a guarantee, or an official interpretation of rules.</p></div></div></section><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{links.map(({ href, label, icon: Icon }) => <Link key={href} href={`/admin/clients/${client.id}/${href}`} className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-[#9db7ee]"><Icon className="text-[#2457d6]" size={21} /><p className="mt-4 font-black">{label}</p><p className="mt-1 text-xs text-zinc-500">Open workspace</p></Link>)}</div><section className="mt-8 rounded-3xl border border-zinc-200 bg-white p-5"><h2 className="text-lg font-black">Primary challenge</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-zinc-600">{client.primary_parking_challenge || "No challenge recorded yet. Start with Intake."}</p></section></main>;
}

function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-zinc-200 bg-white p-4"><p className="text-xs font-bold uppercase tracking-wider text-zinc-400">{label}</p><p className="mt-2 font-black">{value}</p></div>; }
